### ISSUE TITLE
Library doesn't work with Circuitpython 8.0.5

### ISSUE THREAD

**Issue by einstux** [gpongelli/CircuitPython_gpio_expander#2]
I'm trying to get your library to run on `Adafruit CircuitPython 8.0.5 on 2023-03-31; Raspberry Pi Pico W with rp2040`,
and have minimally adjusted the example code (just the I2C-Bus):

```
import board, busio
from gpio_expander import PCA9534, PCA9555
_pca9555 = PCA9555(busio.I2C(scl=board.GP1, sda=board.GP0), 0x74)
print(_pca9555.I0_0)  # pylint: disable=no-member
```

However, this creates an exception:

```
Traceback (most recent call last):
  File "code.py", line 9, in <module>
  File "gpio_expander.py", line 118, in <module>
TypeError: function doesn't take keyword arguments
```

So, something weird is happening, I assume it has to do with your metaclass sorcercy (which I honestly do not understand at all).

With which circuitpython version did you test?
Do you have any clue for me how to fix this?

Thanks,
Tom

**Comment by 4bitFox** [comment]
Have the same exact issue on `adafruit-circuitpython-raspberry_pi_pico2_w-en_US-9.2.6.uf2` when I try to import the library.

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/lib/gpio_expander.py", line 118, in <module>
TypeError: function doesn't take keyword arguments
```
